### ISSUE TITLE
More QEMU architecture?

### ISSUE THREAD

**Issue by leap0x7b** [mjuned47/qemu-termux#1]
I want to emulate other architecture such as RISC-V, PowerPC and SPARC. Can you compile it with that support?

**Comment by mjuned47** [comment]
Yes i can , but right now i dont want to spend time on it 
I tell you how to do it
1) Download qemu source 
2) Install liborc and libspice-server
3) go to qemu source and configure :
    ./configure --target-list={Architecture that you want} --enable-spice
    If you don't know how to set target-list then do :
    ./configure --help and see options available in --target-list

**Comment by mjuned47** [comment]
PPC, RISCV and SPARC architecture added !
Checkout releases
